:py:mod:`CodonU.cua_errors.bad_seq_err`
=======================================

.. py:module:: CodonU.cua_errors.bad_seq_err


Module Contents
---------------

.. py:exception:: BadSequenceError(seq, code)

   Bases: :py:obj:`CodonU.cua_errors.codon_usage_err.CodonUsageError`

   Occurs when the sequence is bad i.e. length of the sequence is not divisible by 3


